//! The menu bar's words, in the languages the site speaks.
//!
//! Like the app's dialogs, the menu follows the system language rather than
//! the site's, as every other application's menu on the machine does.

pub struct MenuWords {
    pub about: &'static str,
    pub settings: &'static str,
    pub services: &'static str,
    pub hide: &'static str,
    pub hide_others: &'static str,
    pub show_all: &'static str,
    pub quit: &'static str,
    pub file: &'static str,
    pub new_drawing: &'static str,
    pub close_window: &'static str,
    pub edit: &'static str,
    pub undo: &'static str,
    pub redo: &'static str,
    pub cut: &'static str,
    pub copy: &'static str,
    pub paste: &'static str,
    pub select_all: &'static str,
    pub search: &'static str,
    pub view: &'static str,
    pub recent: &'static str,
    pub following: &'static str,
    pub communities: &'static str,
    pub together: &'static str,
    pub hashtags: &'static str,
    pub notifications: &'static str,
    pub drafts: &'static str,
    pub profile: &'static str,
    pub back: &'static str,
    pub forward: &'static str,
    pub reload: &'static str,
    pub theme: &'static str,
    pub theme_light: &'static str,
    pub theme_dark: &'static str,
    pub theme_system: &'static str,
    pub full_screen: &'static str,
    pub window: &'static str,
    pub minimize: &'static str,
    pub zoom: &'static str,
    pub bring_all_to_front: &'static str,
    pub help: &'static str,
    pub shortcuts: &'static str,
}

const EN: MenuWords = MenuWords {
    about: "About Oeee Cafe",
    settings: "Settings…",
    services: "Services",
    hide: "Hide Oeee Cafe",
    hide_others: "Hide Others",
    show_all: "Show All",
    quit: "Quit Oeee Cafe",
    file: "File",
    new_drawing: "New Drawing",
    close_window: "Close Window",
    edit: "Edit",
    undo: "Undo",
    redo: "Redo",
    cut: "Cut",
    copy: "Copy",
    paste: "Paste",
    select_all: "Select All",
    search: "Search…",
    view: "View",
    recent: "Recent",
    following: "Following",
    communities: "Communities",
    together: "Draw Together",
    hashtags: "Hashtags",
    notifications: "Notifications",
    drafts: "Drafts",
    profile: "Profile",
    back: "Back",
    forward: "Forward",
    reload: "Reload",
    theme: "Theme",
    theme_light: "Light",
    theme_dark: "Dark",
    theme_system: "System",
    full_screen: "Enter Full Screen",
    window: "Window",
    minimize: "Minimize",
    zoom: "Zoom",
    bring_all_to_front: "Bring All to Front",
    help: "Help",
    shortcuts: "Keyboard Shortcuts",
};

const KO: MenuWords = MenuWords {
    about: "오이카페에 관하여",
    settings: "설정…",
    services: "서비스",
    hide: "오이카페 가리기",
    hide_others: "기타 가리기",
    show_all: "모두 보기",
    quit: "오이카페 종료",
    file: "파일",
    new_drawing: "새 그림",
    close_window: "윈도우 닫기",
    edit: "편집",
    undo: "실행 취소",
    redo: "실행 복귀",
    cut: "오려두기",
    copy: "복사하기",
    paste: "붙여넣기",
    select_all: "전체 선택",
    search: "검색…",
    view: "보기",
    recent: "최신",
    following: "타임라인",
    communities: "커뮤니티",
    together: "함께 그리기",
    hashtags: "해시태그",
    notifications: "알림",
    drafts: "임시 저장",
    profile: "프로필",
    back: "뒤로",
    forward: "앞으로",
    reload: "새로 고침",
    theme: "테마",
    theme_light: "라이트",
    theme_dark: "다크",
    theme_system: "시스템",
    full_screen: "전체 화면 시작",
    window: "윈도우",
    minimize: "최소화",
    zoom: "확대/축소",
    bring_all_to_front: "모두 앞으로 가져오기",
    help: "도움말",
    shortcuts: "키보드 단축키",
};

const JA: MenuWords = MenuWords {
    about: "OEEEカフェについて",
    settings: "設定…",
    services: "サービス",
    hide: "OEEEカフェを隠す",
    hide_others: "ほかを隠す",
    show_all: "すべてを表示",
    quit: "OEEEカフェを終了",
    file: "ファイル",
    new_drawing: "新規お絵かき",
    close_window: "ウインドウを閉じる",
    edit: "編集",
    undo: "取り消す",
    redo: "やり直す",
    cut: "カット",
    copy: "コピー",
    paste: "ペースト",
    select_all: "すべてを選択",
    search: "検索…",
    view: "表示",
    recent: "新着",
    following: "タイムライン",
    communities: "コミュニティ",
    together: "一緒に描く",
    hashtags: "ハッシュタグ",
    notifications: "通知",
    drafts: "下書き",
    profile: "プロフィール",
    back: "戻る",
    forward: "進む",
    reload: "再読み込み",
    theme: "テーマ",
    theme_light: "ライト",
    theme_dark: "ダーク",
    theme_system: "システム",
    full_screen: "フルスクリーンにする",
    window: "ウインドウ",
    minimize: "しまう",
    zoom: "拡大/縮小",
    bring_all_to_front: "すべてを手前に移動",
    help: "ヘルプ",
    shortcuts: "キーボードショートカット",
};

const ZH: MenuWords = MenuWords {
    about: "关于黄瓜咖啡馆",
    settings: "设置…",
    services: "服务",
    hide: "隐藏黄瓜咖啡馆",
    hide_others: "隐藏其他",
    show_all: "全部显示",
    quit: "退出黄瓜咖啡馆",
    file: "文件",
    new_drawing: "新建画作",
    close_window: "关闭窗口",
    edit: "编辑",
    undo: "撤销",
    redo: "重做",
    cut: "剪切",
    copy: "拷贝",
    paste: "粘贴",
    select_all: "全选",
    search: "搜索…",
    view: "显示",
    recent: "最新",
    following: "时间线",
    communities: "社区",
    together: "一起画",
    hashtags: "话题标签",
    notifications: "通知",
    drafts: "草稿",
    profile: "个人资料",
    back: "后退",
    forward: "前进",
    reload: "重新载入",
    theme: "主题",
    theme_light: "浅色",
    theme_dark: "深色",
    theme_system: "跟随系统",
    full_screen: "进入全屏幕",
    window: "窗口",
    minimize: "最小化",
    zoom: "缩放",
    bring_all_to_front: "前置全部窗口",
    help: "帮助",
    shortcuts: "键盘快捷键",
};

pub fn menu_words() -> &'static MenuWords {
    match sys_locale::get_locale().unwrap_or_default().get(..2) {
        Some("ko") => &KO,
        Some("ja") => &JA,
        Some("zh") => &ZH,
        _ => &EN,
    }
}
